// examples/web-wa-sqlite-vuejs/src/ElectricProvider.vue
<script lang="ts" setup>
import { onMounted, shallowRef } from 'vue'
import { LIB_VERSION } from 'electric-sql/version'
import { uniqueTabId } from 'electric-sql/util'
import { ElectricDatabase, electrify } from 'electric-sql/wa-sqlite'
import { authToken } from './auth'
import { provideElectric } from './electric'
import { Electric, schema } from './generated/client'

const electric = shallowRef<Electric>()

onMounted(async () => {
  const config = {
    debug: import.meta.env.DEV,
    url: import.meta.env.ELECTRIC_SERVICE,
  }

  const { tabId } = uniqueTabId()
  const scopedDbName = `basic-${LIB_VERSION}-${tabId}.db`

  const conn = await ElectricDatabase.init(scopedDbName)
  const client = await electrify(conn, schema, config)
  await client.connect(authToken())
  

  // Resolves when the shape subscription has been established.
  const shape = await client.db.items.sync()

  // Resolves when the data has been synced into the local database.
  await shape.synced
  electric.value = client
})

provideElectric(electric)
</script>

<template>
  <div v-if="electric">
    <slot />
  </div>
</template>

// examples/web-wa-sqlite-angular/src/app/electric-provider.component.ts
import { Component, OnInit, signal } from "@angular/core";
import { Electric, schema } from "../generated/client";
import { uniqueTabId } from "electric-sql/util";
import { environment } from "../environments/environment";
import { LIB_VERSION } from "electric-sql/version";
import { authToken } from "./auth";
import { electrify, ElectricDatabase } from 'electric-sql/wa-sqlite'
import { ElectricConfig } from "electric-sql";

@Component({
    selector: 'electric-provider',
    template: `
    @if (electric()) {
        <ng-content />
    }
    `,
    standalone: true
})
export class ElectricProviderComponent implements OnInit {

    electric = signal<Electric | null>(null);
    
    async ngOnInit(): Promise<void> {
        const { tabId } = uniqueTabId()
        const scopedDbName = `basic-${LIB_VERSION}-${tabId}.db`
      
        const config: ElectricConfig = {
          url: environment.ELECTRIC_URL,
          debug: environment.DEV,
        }
      
        const conn = await ElectricDatabase.init(scopedDbName)
      
        const electricClient = await electrify(conn, schema, config)
      
        await electricClient.connect(authToken())
      
        // Resolves when the shape subscription has been established.
        const shape = await electricClient.db.items.sync()
      
        await shape.synced
    }
}
